#自定义配置
arb:
  service:
    name: microservice-loan
    port: 8201

server:
  max-http-header-size: 10240000
  port: ${arb.service.port}
eureka:
  instance:
    instance-id: ${arb.service.url}:${spring.application.name}:${server.port}
    hostname: ${arb.service.url}
    ip-address: ${arb.service.url}
    prefer-ip-address: true

  #    lease-renewal-interval-in-seconds: 10
  #    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck: enabled
    service-url:
      defaultZone: http://${arb.eureka.url}:8901/eureka/
feign:
  client:
    config:
      microservice-payment:
        connectTimeout: 600000
        readTimeout: 600000
      microservice-transaction:
        connectTimeout: 600000
        readTimeout: 600000
      microservice-timeline:
        connectTimeout: 600000
        readTimeout: 600000
      microservice-business:
        connectTimeout: 600000
        readTimeout: 600000
      cache-server:
        connectTimeout: 600000
        readTimeout: 600000
  httpclient:
    connection-timeout: 60000
ribbon:
  read-timout: 60000
  connect-timeout: 60000
  eager-load:
    enabled: true
    clients: microservice-business,cache-server
spring:
  application:
    name: ${arb.service.name}
  datasource:
    driver-class-name: ${arb.database.driver}
    url: ${arb.database.url}
    username: ${arb.database.username}
    password: ${arb.database.password}
    test-on-borrow: true                      # 指明是否从池中取出连接前进行检验，如果检验失败，则从池中取出连接并尝试取出另一个
    test-while-idle: true                     # 指明连接是否被空闲连接回收器（如果有）进行检验，如果检测失败，则连接将被从池中去除
    time-between-eviction-runs-millis: 60000  # 在空闲连接回收器线程运行期间休眠的时间值，姨毫秒为单位。如果设置为非整数，则不运行空闲连接回收器线程
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 256Mb
      max-request-size: 256Mb
  jpa:
    database: mysql  #only worked for mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect #only worked for mysql
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect  #only worked for h2
  rabbitmq:
    host: ${arb.rabbitmq.url}
    port: 5672
    username: ${arb.rabbitmq.username}
    password: ${arb.rabbitmq.password}
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
logging:
  config: classpath:log4j2.yml
---
spring:
  profiles: release
arb:
  eureka:
    url: china-dev.vertical.arbcalls.com
  database:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://china-dev.vertical.arbcalls.com/panda?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: arbfintech
---
spring:
  profiles: develop
arb:
  eureka:
    url: panda.arbfintech.com
  service:
    url: 54.255.235.134
  database:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://arb-panda.cuxwfpxsyc7c.ap-southeast-1.rds.amazonaws.com/panda?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: panda_admin
    password: uGEqetW#a8uEKA2z
  rabbitmq:
    url: rmq.arbfintech.com
    username: panda
    password: 3JU6BvkC^1iI@LN5
---
spring:
  profiles: slave_local
arb:
  eureka:
    url: localhost
  service:
    url: localhost
  database:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100/panda?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    username: Arbfintech
    password: Arbfintech
---
spring:
  profiles: slave-23
arb:
  eureka:
    url: 192.168.0.100
  service:
    url: 192.168.0.23
  database:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100/panda?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: Arbfintech@123
  rabbitmq:
    host: 192.168.0.100
    username: Arbfintech
    password: Arbfintech
---
spring:
  profiles: user-99
arb:
  eureka:
    url: 192.168.0.99
  service:
    url: 192.168.0.99
  database:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100/panda?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    username: Arbfintech
    password: Arbfintech

---
spring:
  profiles: local
arb:
  eureka:
   url: localhost
  service:
   url: localhost
  database:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100/panda?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    username: Arbfintech
    password: Arbfintech
---
spring:
  profiles: test
arb:
  eureka:
    url: localhost
  service:
    url: localhost
  database:
    driver: org.h2.Driver
    url: jdbc:h2:file:~/.h2/testdb
    username: sa
    password:
  rabbitmq:
    host: localhost
    username: Arbfintech
    password: Arbfintech